.TH IRCDAEMON_C 1 "MAY 2011" Linux "User Manuals"
.Os Ubuntu
.SH NAME
.Nm IRCDaemon_C - (c) Wolfgang Dinkel 2011
IRCdaemon_C \- A IRC daemon written in C
.SH SYNOPSIS
.B IRCdaemon [-s 
.I server
.B ] [-c
.I channel
.B ] [-u
.I username/nick
.B ] ...
.SH DESCRIPTION
.B IRCdaemon
An IRC daemon that once started logs all users joining or leaving the channel. Also logs all messages from any user. It is also possible to control the IRC daemon via private message. That way you can get the last logged in user or print a db dump to a log file.
.SH OPTIONS
.IP -D
Do 
.B NOT 
start as a daemon, but as a console app
.IP "-h"
This help
.SH FILES
.I /include/
.RS
libircclient header files

.SH BUGS
The makefiel doesn't seem to include libircclient
.SH AUTHOR
Wolfgang Dinkel <wolfgang.dinkel at fh-heidelberg dot de>
