.Dd 5/29/11					
.Dt IRCDaemon_C				\" program
.Os Darwin
.Sh NAME					
.Nm IRCDaemon_C - (c) Wolfgang Dinkel 2011
.Sh SYNOPSIS				\" required
.Nm
.\" .Op Fl a Ar path \" [-a path] 
.\" .Op Ar file \" [file]
.\" .Op Ar \" [file ...]
.\" .Ar arg0 \" Underlined argument - use .Ar anywhere to underline
-s <server> -u <nick> -c <channel> \" Arguments
.Op Fl d \" [-abcd]
.Sh DESCRIPTION				\" Section Header - required - don't modify
IRCDaemon can connect to any IRC channel and logs the channels activity
.Pp							\" space
List of arguments and flags needed to run and use IRCDaemon:
.Bl -tag -width -indent \" Beginning og tag list
.It <server>
Enter server name or ip address
.It <nick>
Enter the daemons name within the channel
.It <channel>
Enter the channel name
.It Flags: (optional)
-D
do NOT start as a deamon
-h
Help
.El							
.Pp
.Bl -tag -width -indent		
.It Fl d \"-a flag as a list item
Starts the daemon.
.El
.Pp
